# Generated by Django 5.0.6 on 2024-07-07 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_camerastatus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerastatus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
