# Generated by Django 5.0.6 on 2024-07-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_camerastatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='timestamp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
