# Generated by Django 5.0.6 on 2024-07-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_thumbnail_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerastatus',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
