# Generated by Django 5.0.6 on 2024-07-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_camerastatus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='timestamp',
            field=models.CharField(max_length=10),
        ),
    ]
