# Generated by Django 5.0.6 on 2024-07-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_thumbnail_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num_people_limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
